import type { Project } from '@/lib/os';
import type { LineCutNote } from '@/lib/studio';
import type { PlacedNote } from '@/lib/studio/cutlines';
import type { EditorBreakdown } from './breakdown/useEditorBreakdown';

export interface EditorCtx {
  /** Tools this project has reached (a personal script has them all): revisions, breakdown. */
  tools: { revisions: boolean; breakdown: boolean };
  /** Cut notes pinned to lines (Studio › Post), by line index. */
  cutNotes: {
    byLine: Map<number, PlacedNote<LineCutNote>[]>;
    openLine: number | null;
    setOpenLine: (line: number | null) => void;
    resolve: (note: LineCutNote, resolved: boolean) => void;
    canResolve: boolean;
  };
  bd: EditorBreakdown;
  openBreakdown: (elementId?: string | null) => void;
  activeProject: any;
  activeView: any;
  annotationDraft: any;
  annotations: any;
  broadcastCursor: any;
  content: any;
  currentSceneIdx: any;
  currentScript: any;
  cursorLine: any;
  focusMode: any;
  handleEditorChange: any;
  handleEditorKeyDown: any;
  handleExport: any;
  handleLockRevision: any;
  handleNormalize: any;
  handleSave: any;
  highlightRef: any;
  lines: any;
  nightModePreview: any;
  pauseTableRead: any;
  removeAnnotation: any;
  resumeTableRead: any;
  revisionMode: any;
  saving: any;
  sceneWordCounts: any;
  scenesList: any;
  sessionWordsWritten: any;
  setActiveView: any;
  setAnnotationDraft: any;
  setCurrentScript: any;
  setCursorLine: any;
  setFocusMode: any;
  setRevisionMode: any;
  setShowCharBible: any;
  setShowFormatMenu: any;
  setShowRightSidebar: any;
  setShowShortcuts: any;
  setShowSidebar: any;
  showFormatMenu: any;
  showRightSidebar: any;
  showSceneNumbers: any;
  showSidebar: any;
  showWatermark: any;
  startTableRead: any;
  stopTableRead: any;
  submitAnnotation: any;
  tableReadLineIdx: any;
  tableReadPlaying: any;
  textareaRef: any;
  titlePage: any;
  toggleDualDialogue: any;
  typewriterMode: any;
}
