// Builds the SQL that seeds the demo world (scripts/demo/content.ts) into an
// account. Usage:
//
//   npm run demo:sql -- you@example.com [America/Edmonton] > demo.sql
//
// The optional time zone is the account's: shoot days and on-set times are
// written in it (a "today" shoot is rolling when you open it).
//
// then run demo.sql as the database owner (psql, or the Supabase SQL editor).
// It's one DO block, so it applies all or nothing, and it's re-runnable: it
// removes the demo projects it made before and makes them again, fresh — dates
// are relative to the day it runs. Your own projects are never touched.
//
// Rows are written the way the app writes them: each as the person who would
// have made it (request.jwt.claims, so auth.uid() and the guards see them),
// call sheets through issue_call_sheet/ack_call_sheet, and every script's
// scene index exactly as the Studio's sync would compute it from the text.
// Sample people are accounts on @demo.misfitscavern.invalid with no password:
// they can't sign in. They and the demo projects are marked is_sample, which
// keeps them out of public surfaces (platform numbers, the Jobs board, the
// crew directory, recent work) for everyone outside the demo.

import { createHash } from 'node:crypto';
import { parseScript } from '../../lib/scriptos/parser';
import { toPlanRow } from '../../lib/studio/scene-sync';
import { locationKey } from '../../lib/studio/locations';
import { PERSONAS, PROJECTS, WRITING_DAYS, type DemoProject, type Who } from './content';

// --portable: the SQL names no account; it reads the owner from the
// demo.owner setting (set demo.owner = 'you@example.com'), so the file can be
// shared or fetched without carrying anyone's email.
const PORTABLE = process.argv.includes('--portable');
const args = process.argv.slice(2).filter((a) => a !== '--portable');
const email = (args[0] ?? '').trim().toLowerCase();
if (!/^[^@\s]+@[^@\s]+$/.test(email)) {
  console.error('usage: npm run demo:sql -- <account email>');
  process.exit(1);
}

const TZ = (args[1] ?? 'America/Edmonton').trim();
if (!/^[A-Za-z_]+(\/[A-Za-z_+-]+)*$/.test(TZ)) {
  console.error(`not a time zone: ${TZ}`);
  process.exit(1);
}
const DOMAIN = 'demo.misfitscavern.invalid';
const uuid = (key: string) => {
  const h = createHash('md5').update(`misfits-demo:${key}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const idFor = (key: string) => uuid(`${email}:${key}`);
const personaId = (key: string) => uuid(`persona:${key}`);

const q = (v: string | null | undefined) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const n = (v: number | null | undefined) => (v == null ? 'null' : String(v));
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const long = (v: string) => {
  if (v.includes('$txt$')) throw new Error('text contains $txt$');
  return `$txt$${v}$txt$`;
};
/** Local now, local today — in the account's time zone. */
const NOW = `(now() at time zone '${TZ}')`;
const day = (offset: number) => `(${NOW}::date + ${offset})`;
/** A live shoot day starts 150 minutes before the seed runs. */
const LIVE = `date_trunc('minute', ${NOW} - interval '150 minutes')`;
const mins = (hhmm: string) => { const [h, m] = hhmm.split(':').map(Number); return h * 60 + m; };
const ago = (minutes: number) => `(now() - interval '${Math.round(minutes)} minutes')`;
const who = (w: Who) => (w === 'me' ? 'me' : `p_${w}`);
const as = (w: Who) => `perform set_config('request.jwt.claims', json_build_object('sub', ${who(w)}, 'role', 'authenticated')::text, false);`;

const out: string[] = [];
const emit = (s: string) => out.push(s);

emit(PORTABLE
  ? `-- Misfits Cavern demo world. Generated by scripts/demo/build.ts. Run after: set demo.owner = '<account email>';`
  : `-- Misfits Cavern demo world for ${email}. Generated by scripts/demo/build.ts.`);
const OWNER = PORTABLE ? `lower(current_setting('demo.owner'))` : q(email);
const OWNER_NAME = PORTABLE ? 'the demo.owner account' : email.replace(/'/g, "''");
// The SQL is a few DO blocks, each all-or-nothing: the people, then one per
// project, then the writing streak. Small enough to paste into a SQL editor
// one at a time (`--split` writes them apart, separated by a marker line).
const open = () => emit(`DO $demo$
DECLARE
  me uuid;
  pid uuid;
${PERSONAS.map((p) => `  p_${p.key} uuid := '${personaId(p.key)}';`).join('\n')}
BEGIN
  select id into me from auth.users where lower(email) = ${OWNER};
  if me is null then raise exception 'No account for ${OWNER_NAME}'; end if;
`);
const close = () => emit(`  perform set_config('request.jwt.claims', '', false);
END
$demo$;
-- @@block`);
open();

// ── Sample people ────────────────────────────────────────────────────────────
for (const p of PERSONAS) {
  const id = personaId(p.key);
  emit(`  insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
  values ('00000000-0000-0000-0000-000000000000', '${id}', 'authenticated', 'authenticated', ${q(`${p.username}@${DOMAIN}`)}, '', now(), '{"provider":"email","providers":["email"]}', ${j({ username: p.username })}, now() - interval '90 days', now())
  on conflict (id) do nothing;
  update public.profiles set role = ${q(p.craft)}, bio = ${q(p.bio)}, location = ${q(p.location)}, status = 'OPEN', is_sample = true where id = '${id}';`);
}

// ── Clear the last run ───────────────────────────────────────────────────────
const projectIds = PROJECTS.map((p) => idFor(`project:${p.key}`));
const idList = projectIds.map((id) => `'${id}'`).join(', ');
emit(`  -- The previous run's demo projects (and everything hanging off them).
  delete from public.portfolio_projects where source_project_id in (${idList});
  delete from public.jobs where project_id in (${idList});
  delete from public.notifications where user_id = me and (created_by in (select id from auth.users where email like '%@${DOMAIN}') or link ~ '(${projectIds.join('|')})');
  delete from public.projects where id in (${idList});`);

// ── Projects ─────────────────────────────────────────────────────────────────
const SCRIPT_FORMAT: Record<string, string> = { Podcast: 'podcast' };

for (const p of PROJECTS) {
  close();
  open();
  buildProject(p);
}
close();
open();

function buildProject(p: DemoProject) {
  const pid = idFor(`project:${p.key}`);
  const owner = p.owner;
  const P = (k: string) => idFor(`${p.key}:${k}`);
  emit(`\n  -- ── ${p.title} ──`);
  emit(`  pid := '${pid}';`);
  emit(`  ${as(owner)}`);
  const settings = {
    modules: { lounge: true, studio: true, scriptos: true, portfolio: true, distribution: true },
    contentType: SCRIPT_FORMAT[p.format] ?? 'screenplay',
    demo: true,
    ...(p.unlockAll ? { unlockAllTools: true } : {}),
  };
  const festivalSql = p.festivals?.length
    ? `jsonb_build_array(${p.festivals.map((f, i) => `jsonb_build_object('id', ${q(P(`festival:${i}`))}, 'name', ${q(f.name)}, 'status', ${q(f.status)}, 'notes', ${q(f.notes ?? '')}, 'deadline', ${day(f.deadlineOffset)}::text)`).join(', ')})`
    : `'[]'::jsonb`;
  emit(`  insert into public.projects (id, title, description, creator_id, status, accent_color, budget, start_date, end_date, project_type, settings, festival_submissions, visibility, archived_at, created_at, is_sample)
  values (pid, ${q(p.title)}, ${q(p.logline ?? null)}, ${who(owner)}, ${q(p.status)}, ${q(p.accent ?? null)}, ${n(p.budget)}, ${p.startOffset != null ? day(p.startOffset) : 'null'}, ${p.endOffset != null ? day(p.endOffset) : 'null'},
          ${q(p.format)}, ${j(settings)}, ${festivalSql}, ${q(p.visibility)}, ${p.archived ? ago(60 * 24 * 20) : 'null'}, ${ago(60 * 24 * (p.startOffset != null && p.startOffset < 0 ? 30 - p.startOffset : 21))}, true);`);

  for (const [question, value] of Object.entries(p.brief ?? {})) {
    emit(`  insert into public.project_brief (project_id, question, value) values (pid, ${q(question)}, ${j(value)});`);
  }

  // Crew first: their rows below depend on being on the production.
  for (const c of p.crew ?? []) {
    emit(`  insert into public.project_crew (project_id, user_id, role, status, craft, invited_by, created_at) values (pid, ${who(c.who)}, ${q(c.role)}, 'confirmed', ${q(c.craft)}, ${who(owner)}, ${ago(60 * 24 * 14)});`);
  }

  // Script, characters, the scene index as the Studio would build it.
  const sceneIds: string[] = [];
  const sceneNo = (s: number) => {
    const id = sceneIds[s - 1];
    if (!id) throw new Error(`${p.key}: no scene ${s}`);
    return id;
  };
  let scriptId: string | null = null;
  const sceneLocations = new Map<number, string>();
  if (p.script) {
    scriptId = P('script');
    emit(`  insert into public.scripts (id, project_id, title, content, format, created_by, last_edited_by, created_at) values ('${scriptId}', pid, ${q(p.script.title)}, ${long(p.script.text)}, 'screenplay', ${who(owner)}, ${who(owner)}, ${ago(60 * 24 * 12)});`);
    for (const c of p.script.characters ?? []) {
      emit(`  insert into public.script_characters (script_id, name, full_name, age, description, motivation, arc, color, updated_by) values ('${scriptId}', ${q(c.name)}, ${q(c.full_name)}, ${q(c.age)}, ${q(c.description)}, ${q(c.motivation)}, ${q(c.arc)}, ${q(c.color)}, ${who(owner)});`);
    }
    const parsed = parseScript(p.script.text);
    const shootDayOf = new Map<number, number>();
    for (const d of p.schedule ?? []) for (const s of d.scenes) shootDayOf.set(s, d.day);
    parsed.scenes.forEach((scene, i) => {
      const id = P(`scene:${i + 1}`);
      sceneIds.push(id);
      const row = toPlanRow(id, scene, i);
      sceneLocations.set(i + 1, locationKey(row.location));
      const note = p.sceneNotes?.find((x) => x.scene === i + 1);
      emit(`  insert into public.scenes (id, project_id, script_id, scene_number, ordinal, heading, title, location, time_of_day, cast_list, est_duration, shoot_day, status, note, color)
  values ('${id}', pid, '${scriptId}', ${i + 1}, ${i}, ${q(row.heading)}, ${q(row.heading.slice(0, 200))}, ${q(row.location)}, ${q(row.time_of_day)}, ${q(row.cast_list)}, ${q(row.est_duration)}, ${n(shootDayOf.get(i + 1))}, ${p.wrapped?.includes(i + 1) ? `'wrapped'` : 'default'}, ${q(note?.note)}, ${q(note?.color)});`);
    });
    if (p.script.locked) {
      emit(`  insert into public.script_revisions (script_id, color_index, label, snapshot, created_by, created_at) values ('${scriptId}', 0, ${q(p.script.locked)}, ${long(p.script.text)}, ${who(owner)}, ${ago(60 * 24 * 8)});`);
    }
  }

  (p.beats ?? []).forEach((b, i) => {
    emit(`  insert into public.project_beats (project_id, script_id, title, content, color, order_index, created_by) values (pid, ${scriptId ? `'${scriptId}'` : 'null'}, ${q(b.title)}, ${q(b.content)}, ${q(b.color)}, ${i}, ${who(owner)});`);
  });

  (p.refs ?? []).forEach((r, i) => {
    const mid = P(`media:${i}`);
    emit(`  insert into public.media (id, project_id, kind, title, notes, board, external_url, shared, created_by, created_at) values ('${mid}', pid, ${q(r.kind)}, ${q(r.title)}, ${q(r.notes)}, ${q(r.board)}, ${q(r.url)}, ${r.shared ? 'true' : 'false'}, ${who(owner)}, ${ago(60 * 24 * (10 - i * 0.5))});`);
    (r.scenes ?? []).forEach((s, k) => {
      emit(`  insert into public.scene_media (scene_id, media_id, project_id, position, created_by) values ('${sceneNo(s)}', '${mid}', pid, ${k}, ${who(owner)});`);
    });
  });
  for (const a of p.audio ?? []) {
    emit(`  insert into public.project_audio_references (project_id, added_by, reference_type, uri, title, description) values (pid, ${who(owner)}, ${q(a.type)}, ${q(a.uri)}, ${q(a.title)}, ${q(a.description)});`);
  }

  for (const c of p.castings ?? []) {
    emit(`  insert into public.character_castings (project_id, character_name, crew_user_id, created_by) values (pid, ${q(c.character)}, ${who(c.who)}, ${who(owner)});`);
  }

  for (const group of p.shots ?? []) {
    group.shots.forEach((s, i) => {
      emit(`  insert into public.shots (project_id, scene_id, shot_number, shot_size, angle, movement, lens, description, status, order_index, created_by) values (pid, '${sceneNo(group.scene)}', '${i + 1}', ${q(s.size)}, ${q(s.angle)}, ${q(s.movement)}, ${q(s.lens)}, ${q(s.desc)}, ${q(s.status ?? 'planned')}, ${i}, ${who(owner)});`);
    });
  }

  (p.breakdown ?? []).forEach((b, i) => {
    const eid = P(`element:${i}`);
    emit(`  insert into public.breakdown_elements (id, project_id, category_id, name, notes, status, cost, created_by) values ('${eid}', pid, (select id from public.breakdown_categories where project_id = pid and key = ${q(b.category)}), ${q(b.name)}, ${q(b.notes)}, ${q(b.status)}, ${n(b.cost)}, ${who(owner)});`);
    for (const s of b.scenes) emit(`  insert into public.scene_elements (scene_id, element_id, project_id, created_by) values ('${sceneNo(s)}', '${eid}', pid, ${who(owner)});`);
  });

  for (const l of p.locations ?? []) {
    emit(`  insert into public.project_locations (id, project_id, name, address, contact, status, permit, cost, notes, created_by) values ('${P(`location:${l.name}`)}', pid, ${q(l.name)}, ${q(l.address)}, ${q(l.contact)}, ${q(l.status)}, ${q(l.permit)}, ${n(l.cost)}, ${q(l.notes)}, ${who(owner)});`);
  }
  // Every scene location has a record to fill in, as the Locations view shows it.
  for (const name of new Set(sceneLocations.values())) {
    if (!name || (p.locations ?? []).some((l) => l.name === name) || !(p.locations?.length)) continue;
    emit(`  insert into public.project_locations (project_id, name, created_by) values (pid, ${q(name)}, ${who(owner)}) on conflict do nothing;`);
  }

  for (const b of p.budgetLines ?? []) {
    emit(`  insert into public.budget_items (id, project_id, category, description, amount, created_by) values ('${P(`budget:${b.category}`)}', pid, ${q(b.category)}, ${q(b.description)}, ${b.amount}, ${who(owner)});`);
  }
  for (const v of p.vendors ?? []) {
    emit(`  insert into public.vendors (id, project_id, name, category, contact, created_by) values ('${P(`vendor:${v.name}`)}', pid, ${q(v.name)}, ${q(v.category)}, ${q(v.contact)}, ${who(owner)});`);
  }
  for (const e of p.expenses ?? []) {
    emit(`  insert into public.expenses (project_id, budget_item_id, vendor_id, description, amount, status, po_number, spent_on, created_by, created_at) values (pid, '${P(`budget:${e.line}`)}', ${e.vendor ? `'${P(`vendor:${e.vendor}`)}'` : 'null'}, ${q(e.description)}, ${e.amount}, ${q(e.status)}, ${q(e.po)}, ${day(-e.daysAgo)}, ${who(owner)}, ${ago(60 * 24 * e.daysAgo)});`);
  }

  // Call sheets: drafted, their calls, then issued and confirmed as people would.
  for (const d of p.schedule ?? []) {
    const cid = P(`callsheet:${d.day}`);
    // A live day is happening now: its times are anchored to the moment the
    // seed runs; any other day is a date and its local clock times.
    const time = (t: string) => {
      if (!d.live) return q(t);
      let delta = mins(t) - mins(d.general);
      if (delta < -12 * 60) delta += 24 * 60;
      return `(${LIVE} + interval '${delta} minutes')::time`;
    };
    const date = d.live ? `${LIVE}::date` : day(d.offset);
    const at = (minutes: number) => d.live
      ? `((${LIVE} + interval '${minutes} minutes') at time zone '${TZ}')`
      : `((${day(d.offset)} + ${q(d.general)}::time + interval '${minutes} minutes') at time zone '${TZ}')`;
    emit(`  insert into public.call_sheets (id, project_id, shoot_day, shoot_date, general_call, shooting_call, estimated_wrap, location_address, weather, notes, updated_by) values ('${cid}', pid, ${d.day}, ${date}, ${time(d.general)}, ${time(d.shooting)}, ${time(d.wrap)}, ${q(d.address)}, ${q(d.weather)}, ${q(d.notes)}, ${who(owner)});`);
    for (const c of d.calls) {
      emit(`  insert into public.call_sheet_calls (call_sheet_id, project_id, crew_user_id, character_name, role_label, call_time, remarks) values ('${cid}', pid, ${c.who ? who(c.who) : 'null'}, ${q(c.character)}, ${q(c.role)}, ${time(c.time)}, ${q(c.remarks)});`);
    }
    if (d.issue) {
      emit(`  perform public.issue_call_sheet('${cid}', ${q(d.issue.note)});`);
      for (const a of d.acks ?? []) emit(`  ${as(a)}\n  perform public.ack_call_sheet('${cid}');`);
      emit(`  ${as(owner)}`);
    }
    for (const [i, e] of (d.log ?? []).entries()) {
      emit(`  insert into public.set_log (project_id, kind, at, call_sheet_id, scene_id, body, created_by) values (pid, ${q(e.kind)}, ${at(e.at)}, '${cid}', ${e.scene ? `'${sceneNo(e.scene)}'` : 'null'}, ${q(e.body)}, ${who(i % 2 ? owner : (p.crew?.[0]?.who ?? owner))});`);
    }
  }
  for (const c of p.continuity ?? []) {
    emit(`  insert into public.set_log (project_id, kind, at, scene_id, body, created_by) values (pid, 'continuity', ${ago(60 * 24 * c.daysAgo)}, '${sceneNo(c.scene)}', ${q(c.body)}, ${who(c.by)});`);
  }

  // Hours: logged by the person, decided by the owner.
  for (const [i, t] of (p.timesheets ?? []).entries()) {
    const tid = P(`timesheet:${i}`);
    emit(`  ${as(t.who)}
  insert into public.timesheets (id, project_id, user_id, work_date, hours, note) values ('${tid}', pid, ${who(t.who)}, ${day(-t.daysAgo)}, ${t.hours}, ${q(t.note)});
  ${as(owner)}`);
    if (t.status !== 'submitted') emit(`  update public.timesheets set status = ${q(t.status)}, rate = ${n(t.rate)} where id = '${tid}';`);
  }

  for (const t of p.tasks ?? []) {
    emit(`  insert into public.project_tasks (project_id, title, completed, assigned_to, due_date) values (pid, ${q(t.title)}, ${t.done}, ${t.who ? who(t.who) : 'null'}, ${t.dueOffset != null ? day(t.dueOffset) : 'null'});`);
  }
  for (const t of p.timeline ?? []) {
    emit(`  insert into public.timeline_items (project_id, title, description, start_date, end_date, type, status, created_by) values (pid, ${q(t.title)}, ${q(t.description)}, ${day(t.start)}, ${t.end != null ? day(t.end) : 'null'}, ${q(t.type)}, ${q(t.status)}, ${who(owner)});`);
  }

  for (const job of p.jobs ?? []) {
    const jid = P(`job:${job.key}`);
    emit(`  insert into public.jobs (id, project_id, title, description, role, rate, rate_type, status, created_by, character_name, created_at) values ('${jid}', pid, ${q(job.title)}, ${q(job.description)}, ${q(job.role)}, ${n(job.rate)}, ${q(job.rateType ?? 'fixed')}, ${q(job.status)}, ${who(owner)}, ${q(job.character)}, ${ago(60 * 24 * 6)});`);
    for (const a of job.applicants ?? []) {
      emit(`  insert into public.job_applications (job_id, applicant_id, cover_note, status, applied_at) values ('${jid}', ${who(a.who)}, ${q(a.note)}, ${q(a.status)}, ${ago(60 * 24 * a.daysAgo)});
  insert into public.notifications (user_id, type, title, body, link, created_by, created_at) values (${who(owner)}, 'application', ${q(`New application · ${job.title}`.slice(0, 200))}, ${q(a.note.slice(0, 300))}, '/jobs/${jid}', ${who(a.who)}, ${ago(60 * 24 * a.daysAgo)});`);
    }
  }

  if (p.documents?.length) {
    // Paperwork arrived with 20260928100000_documents.sql; skip it where that
    // isn't applied yet (PL/pgSQL resolves the table only if the branch runs).
    emit(`  if to_regclass('public.project_documents') is not null then`);
    for (const d of p.documents) {
      emit(`    insert into public.project_documents (project_id, kind, title, status, person_id, vendor_id, location_id, party, expires_on, notes, created_by) values (pid, ${q(d.kind)}, ${q(d.title)}, ${q(d.status)}, ${d.person ? who(d.person) : 'null'}, ${d.vendor ? `'${P(`vendor:${d.vendor}`)}'` : 'null'}, ${d.location ? `'${P(`location:${d.location}`)}'` : 'null'}, ${q(d.party)}, ${d.expiresOffset != null ? day(d.expiresOffset) : 'null'}, ${q(d.notes)}, ${who(owner)});`);
    }
    emit(`  end if;`);
  }

  for (const [i, c] of (p.cuts ?? []).entries()) {
    const cut = P(`cut:${i}`);
    emit(`  insert into public.post_cuts (id, project_id, title, url, created_by, created_at) values ('${cut}', pid, ${q(c.title)}, ${q(c.url)}, ${who(owner)}, ${ago(60 * 24 * c.daysAgo)});`);
    for (const note of c.notes) {
      emit(`  insert into public.post_notes (project_id, cut_id, scene_id, at_seconds, department, body, created_by, created_at, resolved_at, resolved_by) values (pid, '${cut}', ${note.scene ? `'${sceneNo(note.scene)}'` : 'null'}, ${note.at}, ${q(note.dept)}, ${q(note.body)}, ${who(note.by)}, ${ago(60 * 24 * c.daysAgo - 60)}, ${note.resolved ? ago(60 * 24 * Math.max(c.daysAgo - 2, 0)) : 'null'}, ${note.resolved ? who(owner) : 'null'});`);
    }
  }
  (p.post ?? []).forEach((it, i) => {
    emit(`  insert into public.post_items (project_id, kind, title, department, status, due_date, assigned_to, notes, position, created_by) values (pid, ${q(it.kind)}, ${q(it.title)}, ${q(it.dept ?? null)}, ${q(it.status)}, ${it.dueOffset != null ? day(it.dueOffset) : 'null'}, ${it.who ? who(it.who) : 'null'}, ${q(it.notes)}, ${i}, ${who(owner)});`);
  });

  for (const c of p.campaigns ?? []) {
    emit(`  insert into public.campaigns (project_id, title, platform, status, target_reach, target_demographic, budget, spend, start_date, end_date, notes, created_by) values (pid, ${q(c.title)}, ${q(c.platform)}, ${q(c.status)}, ${q(c.reach)}, ${q(c.demographic)}, ${n(c.budget)}, ${n(c.spend)}, ${c.start != null ? day(c.start) : 'null'}, ${c.end != null ? day(c.end) : 'null'}, ${q(c.notes)}, ${who(owner)});`);
  }

  if (p.portfolio) {
    const fid = P('portfolio');
    const f = p.portfolio;
    emit(`  insert into public.portfolio_projects (id, user_id, title, description, category, year, role, accent_color, source_project_id) values ('${fid}', ${who(owner)}, ${q(f.title)}, ${q(f.description)}, ${q(f.category)}, ${f.year}, ${q(f.role)}, ${q(p.accent ?? null)}, pid);`);
    f.blocks.forEach((b, i) => {
      emit(`  insert into public.portfolio_blocks (portfolio_project_id, position, block_type, title, body, image_url) values ('${fid}', ${i}, ${q(b.type)}, ${q(b.title)}, ${q(b.body)}, ${q(b.image)});`);
    });
  }

  (p.channels ?? []).forEach((c, i) => {
    const chid = P(`channel:${c.name}`);
    emit(`  insert into public.channels (id, project_id, name, type, topic, position, audience, created_by) values ('${chid}', pid, ${q(c.name)}, 'text', ${q(c.topic)}, ${i}, ${q(c.audience)}, ${who(owner)});`);
    for (const m of c.messages) {
      emit(`  insert into public.messages (sender_id, channel_uuid, content, created_at) values (${who(m.who)}, '${chid}', ${q(m.body)}, ${ago(m.minutesAgo)});`);
    }
  });

  // The account was cast in someone else's film: it heard about it.
  for (const c of p.castings ?? []) {
    if (c.who !== 'me' || owner === 'me') continue;
    emit(`  insert into public.notifications (user_id, type, title, body, link, created_by, created_at) values (me, 'crew', ${q(`You’re cast as ${c.character} in ${p.title}`)}, ${q('Welcome aboard. The call sheet is in the project.')}, '/projects/${pid}', ${who(owner)}, ${ago(60 * 24 * 6)});`);
  }
}

// ── The account's own writing streak (never overwrites a real day) ─────────
WRITING_DAYS.forEach((words, i) => {
  if (!words) return;
  const offset = -(WRITING_DAYS.length - i);
  emit(`  insert into public.writing_days (user_id, day, words, sprints, goal) values (me, ${day(offset)}, ${words}, ${Math.max(1, Math.round(words / 250))}, 500) on conflict do nothing;`);
});

close();

process.stdout.write(out.join('\n') + '\n');
