const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const INTEL_DIR = path.join(ROOT_DIR, '.cavern-intelligence');
const MANIFEST_PATH = path.join(INTEL_DIR, 'sync-manifest.json');

const EXCLUDE_DIRS = new Set(['node_modules', '.next', '.git', '.cavern-intelligence', 'dist', 'out', 'test-results', 'playwright-report']);
const INCLUDE_EXTS = new Set(['.ts', '.tsx', '.js', '.jsx', '.json', '.sql', '.md']);

function walk(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    // Skip dangling symlinks (e.g. skills not installed in this checkout).
    const stat = fs.statSync(filePath, { throwIfNoEntry: false });
    if (!stat) continue;
    if (stat.isDirectory()) {
      if (!EXCLUDE_DIRS.has(file)) {
        walk(filePath, fileList);
      }
    } else {
      const ext = path.extname(file).toLowerCase();
      if (INCLUDE_EXTS.has(ext)) {
        fileList.push({
          relPath: path.relative(ROOT_DIR, filePath).replace(/\\/g, '/'),
          size: stat.size,
          mtime: stat.mtime,
          ext: ext
        });
      }
    }
  }
  return fileList;
}

function generateManifest() {
  console.log('Scanning The Cavern codebase...');
  const files = walk(ROOT_DIR);

  // Group files by top-level category
  const categories = {
    app: [],
    components: [],
    lib: [],
    database: [],
    scripts: [],
    config: []
  };

  const fileStats = {
    totalFiles: 0,
    totalSize: 0,
    byExtension: {}
  };

  for (const f of files) {
    fileStats.totalFiles++;
    fileStats.totalSize += f.size;
    fileStats.byExtension[f.ext] = (fileStats.byExtension[f.ext] || 0) + 1;

    if (f.relPath.startsWith('app/')) {
      categories.app.push(f.relPath);
    } else if (f.relPath.startsWith('components/')) {
      categories.components.push(f.relPath);
    } else if (f.relPath.startsWith('lib/')) {
      categories.lib.push(f.relPath);
    } else if (f.relPath.endsWith('.sql')) {
      categories.database.push(f.relPath);
    } else if (f.relPath.startsWith('scripts/')) {
      categories.scripts.push(f.relPath);
    } else {
      categories.config.push(f.relPath);
    }
  }

  // Structured modules overview
  const modules = {
    "ScriptOS Screenplay Engine": {
      description: "Fountain screenplay rendering, AST parsing, real-time sync, revisions and PDF generation",
      path: "lib/scriptos",
      files: categories.lib.filter(p => p.startsWith('lib/scriptos/'))
    },
    "Supabase Client and API Layer": {
      description: "Database queries, RLS wrapper functions, auth services, and real-time chat subscriptions",
      path: "lib/supabase",
      files: categories.lib.filter(p => p.startsWith('lib/supabase/'))
    },
    "WebRTC Voice Engine": {
      description: "Peer-to-peer decentralized crew voice mesh signaling over Supabase Realtime",
      path: "lib/webrtc",
      files: categories.lib.filter(p => p.startsWith('lib/webrtc/'))
    },
    "Next.js Route Structure": {
      description: "App router pages, layouts, custom route middleware and authentication gates",
      path: "app",
      files: categories.app
    },
    "UI Components": {
      description: "Design system buttons, inputs, canvas pins, overlays, and confirmation models",
      path: "components",
      files: categories.components
    },
    "Database Schema & Reference": {
      description: "Postgres schema declarations, indices, and row-level security definitions",
      path: ".",
      files: categories.database
    }
  };

  const manifest = {
    project: "The Cavern",
    last_synchronized: new Date().toISOString(),
    stats: fileStats,
    modules: modules,
    all_monitored_files: files.map(f => ({
      path: f.relPath,
      size: f.size,
      last_modified: f.mtime
    }))
  };

  if (!fs.existsSync(INTEL_DIR)) {
    fs.mkdirSync(INTEL_DIR, { recursive: true });
  }

  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2), 'utf-8');
  console.log(`Successfully compiled sync-manifest.json with ${fileStats.totalFiles} tracked files!`);
}

// ── Agent entry files ───────────────────────────────────────────────────────
// .cavern-intelligence/RULES.md is the one source of the working rules. Each
// tool's entry file is generated from it here, so they can't drift apart:
// Claude imports it (a reference), tools that don't follow links get a mirror,
// Copilot gets a pointer. `--check` (CI) fails if any file is stale or edited.
const RULES_PATH = path.join(INTEL_DIR, 'RULES.md');
const NOTE = '<!-- GENERATED by `npm run sync-intel` from .cavern-intelligence/RULES.md. Do not edit: change RULES.md (or the tool-specific lines in scripts/sync-intel.js). -->';

function adapters() {
  const rules = fs.readFileSync(RULES_PATH, 'utf8');
  // Links in RULES.md are relative to .cavern-intelligence/; the mirror lives at the root.
  const mirrored = rules.replace(/\]\((?!https?:|#|\.\.?\/|\/)([^)]+)\)/g, '](.cavern-intelligence/$1)');
  return {
    'AGENTS.md': `${NOTE}

> For Codex, Cursor, Cline, Windsurf, Zed, Gemini, Jules and Copilot's agent.
> File names in backticks are in \`.cavern-intelligence/\` unless a path is given.

${mirrored}`,
    'CLAUDE.md': `${NOTE}

# Claude Code — The Cavern

@.cavern-intelligence/RULES.md

@.cavern-intelligence/STATE.md

## Claude-only notes

- **Harness**: \`.claude/settings.json\` (committed) — MCP servers, and which
  actions run without asking, ask, or are denied. What each one is and why:
  \`.cavern-intelligence/tools-and-access.md\` §2–3. Don't restate them here.
- **Skills**: \`.claude/skills/\` — \`run-misfits-cavern\` (run, test and
  drive the suite), \`supabase\`, \`supabase-postgres-best-practices\`.
- Every open task: \`.cavern-intelligence/BACKLOG.md\`. The map:
  \`.cavern-intelligence/INDEX.md\`.
`,
    '.github/copilot-instructions.md': `${NOTE}

# The Cavern — instructions for GitHub Copilot

The working rules for this repository are in
[\`.cavern-intelligence/RULES.md\`](../.cavern-intelligence/RULES.md) (mirrored
in [\`AGENTS.md\`](../AGENTS.md)). Current work: \`.cavern-intelligence/STATE.md\`
and \`BACKLOG.md\`. The map: \`.cavern-intelligence/INDEX.md\`.

Short version: no mocks; verify with typecheck, lint, tests and build; toasts
and the confirm dialog, never \`alert\`/\`confirm\`; RLS on every table;
migrations are the schema; feature branches and PRs, never \`main\`.
`,
  };
}

function writeAdapters() {
  for (const [rel, body] of Object.entries(adapters())) {
    fs.mkdirSync(path.dirname(path.join(ROOT_DIR, rel)), { recursive: true });
    fs.writeFileSync(path.join(ROOT_DIR, rel), body, 'utf-8');
  }
  console.log('Agent entry files written: AGENTS.md, CLAUDE.md, .github/copilot-instructions.md');
}

function checkAdapters() {
  const stale = Object.entries(adapters())
    .filter(([rel, body]) => !fs.existsSync(path.join(ROOT_DIR, rel)) || fs.readFileSync(path.join(ROOT_DIR, rel), 'utf8') !== body)
    .map(([rel]) => rel);
  if (stale.length) {
    console.error(`Out of sync with .cavern-intelligence/RULES.md: ${stale.join(', ')}. Run \`npm run sync-intel\` and commit.`);
    process.exit(1);
  }
  console.log('Agent entry files match RULES.md.');
}

if (process.argv.includes('--check')) {
  checkAdapters();
} else {
  generateManifest();
  writeAdapters();
}
